package com.example.demo.entity;
// Generated 2025/04/20 15:17:22 by Hibernate Tools 6.5.1.Final

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

import lombok.Data;

/**
 * Products generated by hbm2java
 */
@Data
@Entity
public class Products implements java.io.Serializable {

    @Id
    private String itemCode;
    private Integer genreId;
    private String name;
    private String imageUrl;
    private Integer price;
    private String itemUrl;
    private int deleteFlg;
    private LocalDate createdDate;
    private LocalDate updatedDate;

    public Products() {
    }

    public Products(String itemCode, int deleteFlg, LocalDate createdDate) {
	this.itemCode = itemCode;
	this.deleteFlg = deleteFlg;
	this.createdDate = createdDate;
    }

    public Products(String itemCode, Integer genreId, String name, String imageUrl, Integer price, String itemUrl,
	    int deleteFlg, LocalDate createdDate) {
	this.itemCode = itemCode;
	this.genreId = genreId;
	this.name = name;
	this.imageUrl = imageUrl;
	this.price = price;
	this.itemUrl = itemUrl;
	this.deleteFlg = deleteFlg;
	this.createdDate = createdDate;
    }

    public String getItemCode() {
	return this.itemCode;
    }

    public void setItemCode(String itemCode) {
	this.itemCode = itemCode;
    }

    public Integer getGenreId() {
	return this.genreId;
    }

    public void setGenreId(Integer genreId) {
	this.genreId = genreId;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getImageUrl() {
	return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
	this.imageUrl = imageUrl;
    }

    public Integer getPrice() {
	return this.price;
    }

    public void setPrice(Integer price) {
	this.price = price;
    }

    public String getItemUrl() {
	return this.itemUrl;
    }

    public void setItemUrl(String itemUrl) {
	this.itemUrl = itemUrl;
    }


    public int getDeleteFlg() {
	return this.deleteFlg;
    }

    public void setDeleteFlg(int deleteFlg) {
	this.deleteFlg = deleteFlg;
    }

    public LocalDate getCreatedDate() {
	return this.createdDate;
    }

    public void setCreatedDate(LocalDate createdDate) {
	this.createdDate = createdDate;
    }

    public LocalDate getUpdatedDate() {
	return this.updatedDate;
    }

    public void setUpdatedDate(LocalDate updatedDate) {
	this.updatedDate = updatedDate;
    }

}
