package com.example.demo.entity;
// Generated 2025/04/06 16:23:55 by Hibernate Tools 6.5.1.Final

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * TierRanks generated by hbm2java
 */
@Entity
public class TierRanks implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // 自動生成されるIDを指定
    private long id;
    private String itemCode;
    private int petId;
    private String uid;
    private String tierCategory;
    private char tierRank;
    private int rankInTier;
    private int deleteFlg;
    private LocalDate createdDate;
    private LocalDate updatedDate;

    public TierRanks() {
    }

    /**
     * 新規登録用のコンストラクタ
     * 
     * @param productId
     * @param petId
     * @param uid
     * @param tierCategory
     * @param tierRank
     * @param rankInTier
     * @param deleteFlg
     * @param createdDate
     */
    public TierRanks(String itemCode, int petId, String uid, String tierCategory, char tierRank,
	    int rankInTier, int deleteFlg, LocalDate createdDate) {
	this.itemCode = itemCode;
	this.petId = petId;
	this.uid = uid;
	this.tierCategory = tierCategory;
	this.tierRank = tierRank;
	this.rankInTier = rankInTier;
	this.deleteFlg = deleteFlg;
	this.createdDate = createdDate;
    }

    public TierRanks(long id, String itemCode, int petId, String uid, String tierCategory, char tierRank,
	    int rankInTier, int deleteFlg, LocalDate createdDate, LocalDate updatedDate) {
	this.id = id;
	this.itemCode = itemCode;
	this.petId = petId;
	this.uid = uid;
	this.tierCategory = tierCategory;
	this.tierRank = tierRank;
	this.rankInTier = rankInTier;
	this.deleteFlg = deleteFlg;
	this.createdDate = createdDate;
	this.updatedDate = updatedDate;
    }

    /**
     * tier表取得用のコンストラクタ
     * 
     * @param petId
     * @param tierCategory
     */
    public TierRanks(int petId, String tierCategory) {
	this.petId = petId;
	this.tierCategory = tierCategory;

    }

    public long getId() {
	return this.id;
    }

    public void setId(long id) {
	this.id = id;
    }

    public String getItemCode() {
	return this.itemCode;
    }

    public void setItemCode(String itemCode) {
	this.itemCode = itemCode;
    }

    public int getPetId() {
	return this.petId;
    }

    public void setPetId(int petId) {
	this.petId = petId;
    }

    public String getUid() {
	return this.uid;
    }

    public void setUid(String uid) {
	this.uid = uid;
    }

    public String getTierCategory() {
	return this.tierCategory;
    }

    public void setTierCategory(String tierCategory) {
	this.tierCategory = tierCategory;
    }

    public char getTierRank() {
	return this.tierRank;
    }

    public void setTierRank(char tierRank) {
	this.tierRank = tierRank;
    }

    public int getRankInTier() {
	return this.rankInTier;
    }

    public void setRankInTier(int rankInTier) {
	this.rankInTier = rankInTier;
    }

    public int getDeleteFlg() {
	return this.deleteFlg;
    }

    public void setDeleteFlg(int deleteFlg) {
	this.deleteFlg = deleteFlg;
    }

    public LocalDate getCreatedDate() {
	return this.createdDate;
    }

    public void setCreatedDate(LocalDate createdDate) {
	this.createdDate = createdDate;
    }

    public LocalDate getUpdatedDate() {
	return this.updatedDate;
    }

    public void setUpdatedDate(LocalDate updatedDate) {
	this.updatedDate = updatedDate;
    }

}
