package com.example.demo.entity;
// Generated 2025/01/20 20:57:37 by Hibernate Tools 6.5.1.Final

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

/**
 * Users generated by hbm2java
 */
@Entity
public class Users implements java.io.Serializable {
    @Id
	private String uid;

	private String userName;
	private Integer petsNum;
	private LocalDate registeredDate;
	private Integer deleteFlg;
	private LocalDate createdDate;
	private LocalDate updatedDate;

	public Users() {
	}

	public Users(String uid, LocalDate registeredDate, LocalDate createdDate) {
		this.uid = uid;
		this.registeredDate = registeredDate;
		this.createdDate = createdDate;
	}

	public Users(String uid, String userName, Integer petsNum, LocalDate registeredDate, Integer deleteFlg,
		LocalDate createdDate,
		LocalDate updatedDate) {
		this.uid = uid;
		this.userName = userName;
		this.petsNum = petsNum;
		this.registeredDate = registeredDate;
		this.deleteFlg = deleteFlg;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getPetsNum() {
		return this.petsNum;
	}

	public void setPetsNum(Integer petsNum) {
		this.petsNum = petsNum;
	}

	public LocalDate getRegisteredDate() {
		return this.registeredDate;
	}

	public void setRegisteredDate(LocalDate localDate) {
	    this.registeredDate = localDate;
	}

	public Integer getDeleteFlg() {
		return this.deleteFlg;
	}

	public void setDeleteFlg(Integer deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	public LocalDate getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(LocalDate localDate) {
	    this.createdDate = localDate;
	}

	public LocalDate getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(LocalDate localDate) {
	    this.updatedDate = localDate;
	}

}
